### ISSUE TITLE
Results_Final/warped_source.tif is missing and unsaved

### ISSUE THREAD

**Issue by LuoSihao-Simon** [MWod/DeeperHistReg#10]
When I reproduced the program, I got the following error：
warped_name = [item for item in os.listdir(pathlib.Path(save_path) / experiment_name / "Results_Final") if "warped_source" in item][0]
IndexError: list index out of range
After debugging, I realised that the problem occured because the [Results_Final/warped_source.tif] was not generated and saved.
However, warped_source.jpg in other folders (e.g. initial_Registration , Nongid_Registration) are successfully saved! In addition, displacement_field.mha and postprocessing_params.json in the Results_Final folder are also generated.

This error can of course be avoided by setting ‘save_final_images’: false，but I need the final warped_source.tif image.

My input and output image format is TIF.
"loader": "pil",
"saver": "pil",
"final_saver": "tiff",
"save_params": "pil",
"extension": ".jpg",
"final_extension": ".tif"
I have no idea what the reason for the problem is, and the program doesn't run in the code that saves the image when debugging, can you help me, thank you very much!

![图片](https://github.com/user-attachments/assets/e7d8ee0a-3dcf-468e-b224-6b2f329d6296)

**Comment by LuoSihao-Simon** [comment]
I tried to use apply_deformation.py directly , input the source and target images and displacement_field.mha, but I get the error: 

pyvips.error.Error: unable to call openslideload
  openslide2vips: unsupported slide format
It looks like the loader =deeperhistreg.loaders.OpenSlideLoader function doesn't support loading the image
Does it not support single channel greyscale images in TIF format?

**Comment by MWod** [comment]
The error is quite strange. If you were able to load the image during the registration phase, you should be able to load it also during applying the deformation. 

The OpenSlideLoader loads all formats that are supported by OpenSlide. It seems that your file is not compatible with OpenSlide - you can verify whether other loaders (e.g. PIL or PyVips) will work for you or modify the input image (e.g. to be RGB image with all channels containing the same intensity).

Note that the intermediate results are saved only for debugging purposes in low resolution and you can turn this feature off by modifying the config - they are saved in compressed .jpg format using the PIL library.

Bests,

**Comment by LuoSihao-Simon** [comment]
> The error is quite strange. If you were able to load the image during the registration phase, you should be able to load it also during applying the deformation.
> 
> The OpenSlideLoader loads all formats that are supported by OpenSlide. It seems that your file is not compatible with OpenSlide - you can verify whether other loaders (e.g. PIL or PyVips) will work for you or modify the input image (e.g. to be RGB image with all channels containing the same intensity).
> 
> Note that the intermediate results are saved only for debugging purposes in low resolution and you can turn this feature off by modifying the config - they are saved in compressed .jpg format using the PIL library.
> 
> Bests,

Thank you very much, I was able to load the image by using the PILloader,
![图片](https://github.com/user-attachments/assets/36b86f7e-66b9-4d9c-8727-492cfe0fbdc3)

 but I got the following error when using both apply_deformation.py :
```
Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/DR/lib/python3.10/site-packages/pyvips/vimage.py", line 1339, in __getattr__
    Introspect.get(name)
  File "/home/simon/anaconda3/envs/DR/lib/python3.10/site-packages/pyvips/voperation.py", line 153, in get
    cls._introspect_cache[operation_name] = Introspect(operation_name)
  File "/home/simon/anaconda3/envs/DR/lib/python3.10/site-packages/pyvips/voperation.py", line 39, in __init__
    op = Operation.new_from_name(operation_name)
  File "/home/simon/anaconda3/envs/DR/lib/python3.10/site-packages/pyvips/voperation.py", line 193, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))

pyvips.error.Error: no such operation gravity
  VipsOperation: class "gravity" not found
```
And I get a similar error when debug run.py, Ifound this because the **gravity** attribute is not supported in the following code, I have installed pyvips==2.2.1, is there something wrong with this library's ？“ image_1 = image_1.gravity and image_2 = image_2.gravity”

```
`def pad_to_same_size_pyvips(image_1 : pyvips.Image, image_2 : pyvips.Image, pad_value : float=1.0) -> Tuple[pyvips.Image, pyvips.Image, dict]:
    """
    TODO
    """
    y_size_1, x_size_1 = image_1.height, image_1.width
    y_size_2, x_size_2 = image_2.height, image_2.width
    pad_1, pad_2 = calculate_pad_value((y_size_1, x_size_1), (y_size_2, x_size_2))
    image_1 = image_1.gravity("centre", x_size_1 + pad_1[1][0] + pad_1[1][1], y_size_1 + pad_1[0][0] + pad_1[0][1], background=[pad_value, pad_value, pad_value])
    image_2 = image_2.gravity("centre", x_size_2 + pad_2[1][0] + pad_2[1][1], y_size_2 + pad_2[0][0] + pad_2[0][1], background=[pad_value, pad_value, pad_value])
    padding_params = dict()
    padding_params['pad_1'] = pad_1
    padding_params['pad_2'] = pad_2
    return image_1, image_2, padding_params`
```
And In the save_final phase, self.source, self.target, and slef.warped_source are all NONE.
![图片](https://github.com/user-attachments/assets/94399ec2-f633-4890-aa0a-e3ae12d22cce)

**Comment by LuoSihao-Simon** [comment]
I was able to save the final warped_source image by blocking the pad_to_same_size_pyvips function, and I think that's reasonable since I'm always inputting image pairs of the same size. But the issue of the gravity attribute not being supported with pyvips==2.2.1 is still unresolved.
![图片](https://github.com/user-attachments/assets/63b84965-31a7-4012-8030-fbe702953dc7)

**Comment by MWod** [comment]
Ok, thanks for the feedback. Actually that's the first time I see the problem and need to verify what is the potential source. It may be connected both the PyVips but also to the input data format and some missing properties. 

Another guess is that the library (the original vips) is actually not installed/compiled correctly. What operating system are you using? How did you install the vips library?

**Comment by LuoSihao-Simon** [comment]
> Ok, thanks for the feedback. Actually that's the first time I see the problem and need to verify what is the potential source. It may be connected both the PyVips but also to the input data format and some missing properties.
> 
> Another guess is that the library (the original vips) is actually not installed/compiled correctly. What operating system are you using? How did you install the vips library?

Thank you for your patience and help, the system I use is ubuntu 20.04 LTS, I install vips by command
`pip install  PyVips==2.2.2`, 
part of my environment is shown below:
![图片](https://github.com/user-attachments/assets/0e0d901a-5a4a-4a69-8745-62810b5cc731)

**Comment by MWod** [comment]
Hello,

Sorry for the late response.

I attempted to reproduce the issue but without success. Previously I was using pyvips '2.2.1'. However, I also attempted to use '2.2.2' as in your environment - and I could not reproduce the issue. 

Please try to downgrade your PyVips version to '2.2.1'.

Moreover, please remember about installing the libvips separately:

`sudo apt install libvips-dev --no-install-recommends`

or visit: https://www.libvips.org/install.html for more details.

Bests,

**Comment by LuoSihao-Simon** [comment]
> Hello,
> 
> Sorry for the late response.
> 
> I attempted to reproduce the issue but without success. Previously I was using pyvips '2.2.1'. However, I also attempted to use '2.2.2' as in your environment - and I could not reproduce the issue.
> 
> Please try to downgrade your PyVips version to '2.2.1'.
> 
> Moreover, please remember about installing the libvips separately:
> 
> `sudo apt install libvips-dev --no-install-recommends`
> 
> or visit: https://www.libvips.org/install.html for more details.
> 
> Bests,

Thanks a lot for your time and that's very kind of you, I'll have a try at your solution, thanks again!
