### ISSUE TITLE
Questions about how to find corresponding coordinates between source image and target image

### ISSUE THREAD

**Issue by YimengQiao** [MWod/DeeperHistReg#12]
Dear authors,

Thanks for your fantastic work! I think this model is very suitable for H&E image registration.

I have two H&E images, one serving as the source image, and another as the fixed image. I tried your deeperhistreg model and got a registered image that looked perfect to my naked eye.

Now, I want to achieve a task that given a point on the source image, returns the corresponding coordinate on the target image. I noticed that you gave an example of applying transformation in another issue, as a result, I tried the following codes. However, I found that the returned coordinates seemed not to be in the same location on the two H&E images, could you please help find the problem? I don't know if there is something wrong with my understanding.

`source image shape: (7590, 7606, 3)`
`target image shape: (7688, 7817, 3)`

I marked a point on the original source image as a landmark:

`landmarks = np.array([[5833,4600])`

```
def warp_landmarks(landmarks, displacement_field, postprocessing_params):
    source_pad = postprocessing_params['pad_1']
    target_pad = postprocessing_params['pad_2']
    source_resample_ratio = postprocessing_params['source_resample_ratio']
    target_resample_ratio = postprocessing_params['target_resample_ratio']
    initial_resampling = postprocessing_params['initial_resampling']
    if initial_resampling:
        initial_resample_ratio = postprocessing_params['initial_resample_ratio']
    y_pad = target_pad[0]
    x_pad = target_pad[1]
    landmarks = landmarks * target_resample_ratio
    landmarks[:, 0] = landmarks[:, 0] + x_pad[0]
    landmarks[:, 1] = landmarks[:, 1] + y_pad[0]
    if initial_resampling:
        landmarks = landmarks / initial_resample_ratio
    warped_landmarks = warp_landmarks_w(landmarks, displacement_field)
    if initial_resampling:
        warped_landmarks = warped_landmarks * initial_resample_ratio
    y_pad = source_pad[0]
    x_pad = source_pad[1]
    warped_landmarks[:, 0] = warped_landmarks[:, 0] - x_pad[0]
    warped_landmarks[:, 1] = warped_landmarks[:, 1] - y_pad[0]
    warped_landmarks = warped_landmarks / source_resample_ratio
    return warped_landmarks
```

And then I tried to apply this transformation
```
warped_landmarks = warp_landmarks(landmarks, displacement_field, postprocessing_params)
```

And got `warped_landmarks: [5779.59061909, 4606.4391183]`.

To my understanding, the `landmark` and the `warped_landmark` should lie in the same location both on the source image and the registered image, however, on the source image, the given point `landmark` is within the yellow rectangle

<img width="326" alt="截屏2024-12-06 16 26 28" src="https://github.com/user-attachments/assets/b2d86fd3-ea05-4303-872b-0fd11d438282">

while the transformed point `warped_landmark` is within the yellow rectangle on the registered image like this

<img width="290" alt="截屏2024-12-06 16 30 05" src="https://github.com/user-attachments/assets/019dcd4c-954c-4942-8e3d-19b03ddbac0e">

I really appreciate your kind help:) Looking forward to your reply!

**Comment by MWod** [comment]
Let's start from a sanity question: Are the transformed landmarks annotated in the source or the target image?

Image registration usually assumed backward warping - so if you want to transform landmarks annotated in the source image - you should register target to source - and vice-versa. So if you would like to transform the source landmarks - register target to source. If you want to transform the target landmarks - register source to target.

Hope it helps and will solve the issue!

Bests,

**Comment by YimengQiao** [comment]
Thanks for answering my stupid question:) I think I misunderstood image registration before.

So here I annotated a landmark on image A, if I want to transform this landmark on image A to get the corresponding coordinates on image B, I need to register image B to image A. That is, I should set the `config['source_path']=imageB_path` and `config['target_path']=imageA_path`, is this correct?

I still used the two images shown above, then I have:
```
source image shape: (7688, 7817, 3)
target image shape: (7590, 7606, 3)
```

After registration, I got a warped source image shaped `(7590, 7606, 3)`.

I have a landmark annotated on the target image and the coordinate is `(5836, 4595)`. Applied transformation using the `warp_landmarks()` function, I got the returned coordinate `(5782.75, 4601.62)`. I am wondering is this coordinate on the source image or on the warped source image. I found this returned coordinate seemed not to correspond to the landmark in either the source image or the warped source image. Could you please help me to find the problem? I am really confused by image registration and so sorry for wasting your time~~

**Comment by MWod** [comment]
In the setup you describe - the landmarks should be correctly placed in the original source image. Is the landmark far from the expected position? Were the images registered correctly (by visual inspection)? Is the ordering of x and y coordinates correct?

**Comment by YimengQiao** [comment]
Thanks for your kind help:)

Here I have a source image like this
![image](https://github.com/user-attachments/assets/9f178bae-ee2d-4eca-9ae9-fe3161240476)
 And the target image like this
![image](https://github.com/user-attachments/assets/77080db8-df85-4bc3-ad8c-1996d6fee68d)

After registration, I merged the warped source image (blue channel, translucent, on the top) and the target image (H&E RGB channel, at the bottom) together. I think the registration looks excellent by visual inspection.
![image](https://github.com/user-attachments/assets/0b85d9b7-58c8-4d59-a3e2-db6dc564539f)

Then I annotated a point on the target image shown in the yellow rectangle, the coordinate is `(5835, 4596.5)`.
![image](https://github.com/user-attachments/assets/4bde2455-878e-4977-a308-a4cb1334dc50)

I tried to apply transformation in the following way:
```
landmarks = np.array([[5835, 4596.5]])
warped_landmarks = warp_landmarks(landmarks, displacement_field, postprocessing_params)
```

where the `warp_landmarks()` function is defined as
```
def warp_landmarks(landmarks, displacement_field, postprocessing_params):
    source_pad = postprocessing_params['pad_1']
    target_pad = postprocessing_params['pad_2']
    source_resample_ratio = postprocessing_params['source_resample_ratio']
    target_resample_ratio = postprocessing_params['target_resample_ratio']
    initial_resampling = postprocessing_params['initial_resampling']
    if initial_resampling:
        initial_resample_ratio = postprocessing_params['initial_resample_ratio']
    y_pad = target_pad[0]
    x_pad = target_pad[1]
    landmarks = landmarks * target_resample_ratio
    landmarks[:, 0] = landmarks[:, 0] + x_pad[0]
    landmarks[:, 1] = landmarks[:, 1] + y_pad[0]
    if initial_resampling:
        landmarks = landmarks / initial_resample_ratio
    warped_landmarks = warp_landmarks_w(landmarks, displacement_field)
    if initial_resampling:
        warped_landmarks = warped_landmarks * initial_resample_ratio
    y_pad = source_pad[0]
    x_pad = source_pad[1]
    warped_landmarks[:, 0] = warped_landmarks[:, 0] - x_pad[0]
    warped_landmarks[:, 1] = warped_landmarks[:, 1] - y_pad[0]
    warped_landmarks = warped_landmarks / source_resample_ratio
    return warped_landmarks

def warp_landmarks_w(landmarks : np.ndarray, displacement_field : np.ndarray) -> np.ndarray:
    landmarks_x = landmarks[:, 0]
    landmarks_y = landmarks[:, 1]
    ux = map_coordinates(displacement_field[0, :, :], [landmarks_y, landmarks_x], mode='nearest')
    uy = map_coordinates(displacement_field[1, :, :], [landmarks_y, landmarks_x], mode='nearest')
    new_landmarks = np.stack((landmarks_x + ux, landmarks_y + uy), axis=1)
    return new_landmarks

def map_coordinates(input, coordinates, output=None, order=3,
                    mode='constant', cval=0.0, prefilter=True):
    if order < 0 or order > 5:
        raise RuntimeError('spline order not supported')
    # I customized the map_coordinates in the scipy.ndimage, change input=numpy.asarray(input) into sitk.GetArrayFromImage(input), otherwise, the coordinates.shape[0] would be 2 while the input.ndim would be 1 
    # input = numpy.asarray(input)
    input = sitk.GetArrayFromImage(input)
    coordinates = numpy.asarray(coordinates)
    if numpy.iscomplexobj(coordinates):
        raise TypeError('Complex type not supported')
    output_shape = coordinates.shape[1:]
    if input.ndim < 1 or len(output_shape) < 1:
        raise RuntimeError('input and output rank must be > 0')
    if coordinates.shape[0] != input.ndim:
        raise RuntimeError('invalid shape for coordinate array')
    complex_output = numpy.iscomplexobj(input)
    output = _ni_support._get_output(output, input, shape=output_shape,
                                     complex_output=complex_output)
    if complex_output:
        kwargs = dict(order=order, mode=mode, prefilter=prefilter)
        map_coordinates(input.real, coordinates, output=output.real,
                        cval=numpy.real(cval), **kwargs)
        map_coordinates(input.imag, coordinates, output=output.imag,
                        cval=numpy.imag(cval), **kwargs)
        return output
    if prefilter and order > 1:
        padded, npad = _prepad_for_spline_filter(input, mode, cval)
        filtered = spline_filter(padded, order, output=numpy.float64,
                                 mode=mode)
    else:
        npad = 0
        filtered = input
    mode = _ni_support._extend_mode_to_code(mode)
    _nd_image.geometric_transform(filtered, None, coordinates, None, None,
                                  output, order, mode, cval, npad, None, None)
    return output
```

And finally, I got a warped landmark coordinate `(5888.33132744, 4589.83384514)`, and this point is in the yellow rectangle on the original source image like this
![image](https://github.com/user-attachments/assets/978d1c15-1f53-4cfb-8d74-e5932093ccbd)

I am confused because I think this is not too far from expectation, however, it seems to be different from the registered image shown above. So I am wondering whether there was something I misunderstood and would like to seek for your help.

**Comment by MWod** [comment]
That's quite strange. Can you try to swap the X and Y coordinate before and after applying the warp landmarks function? I mean - is the landmark annotated in row/column or column/row order?

**Comment by YimengQiao** [comment]
Thanks for your prompt response!!

After swapping the X and Y coordinates before and after applying the warp landmarks function, I used the same landmark on the target image and got a point on the original source image as shown in the figure.

On the target image, I annotated a point within the yellow rectangle reigon
![image](https://github.com/user-attachments/assets/29b9d4b9-c66f-4ccb-a1fb-a8e86509f4b3)

On the original source image, I annotated the transformed landmarks
![image](https://github.com/user-attachments/assets/d48cac19-50a6-4f2b-9c3f-efbe10ae0d76)
The point within the red rectangle is the transformed landmark before swapping X and Y, while the point within the yellow rectangle is the transformed landmark after swapping X and Y. I think both of them looked a little bit far from expectation and I didn't find the exact reason.

**Comment by MWod** [comment]
Can you please overlay the zoomed transformed source image on the target image to verify whether they are correctly aligned - to verify that the problem is not connected simply with incorrect registration? Do the postprocessing params come from the source to target or target to source registration?

The warping function assumes that the landmarks are annotated using the X, Y convention (column first). 

Moreover, I think that the modification to use SimpleITK may introduce an error. I suggest to use the original one but to ensure that your landmarks array is 2-D (number of landmarks X 2) - I suggest to define at least 2 landmarks to avoid a potential error message.

**Comment by YimengQiao** [comment]
Thank you sooo much!! The problem exactly lies in using SimpleITK for array conversion.  I changed to the default setting and it worked perfectly. Really appreciate your kind help and thanks for your great model!!
