### ISSUE TITLE
Does this deeperhistreg also support gigapiexel image registration

### ISSUE THREAD

**Issue by Fighting-bruceCHN** [MWod/DeeperHistReg#5]
Hi,

i want to ask if the deeperhistreg or deephistreg support the gigapixel image registration (80000*60000) for example, and both these two repos are aimed for full-resolution or ? 

Warm regards 
Aobo

**Comment by MWod** [comment]
Hi,

DeeperHistReg is greatly expanded version of DeepHistReg - I suggest to use just the DeeperHistReg.

The currently released version allow one to perform warping of images up to ~200k x 200k, however the registration is performed on lower resolution (up to maximum about 20k x 20k, depending on the available hardware). It is enough for consecutive slides - the registration accuracy is not increased further by increasing the resolution used for registration.

However, we are working currently on expanding the framework with patch-based pipeline that will allow full-resolution registration, e.g. for restained slides. It should be released in September / October. 

Bests,

**Comment by Fighting-bruceCHN** [comment]
> Hi,
> 
> DeeperHistReg is greatly expanded version of DeepHistReg - I suggest to use just the DeeperHistReg.
> 
> The currently released version allow one to perform warping of images up to ~200k x 200k, however the registration is performed on lower resolution (up to maximum about 20k x 20k, depending on the available hardware). It is enough for consecutive slides - the registration accuracy is not increased further by increasing the resolution used for registration.
> 
> However, we are working currently on expanding the framework with patch-based pipeline that will allow full-resolution registration, e.g. for restained slides. It should be released in September / October.
> 
> Bests,

Thank you so much for the quick reply and the Maintenance of the library for continuous improvement 
Looking forward for your new release
All the best,
