### ISSUE TITLE
how to organize the dataset?

### ISSUE THREAD

**Issue by LuoSihao-Simon** [MWod/DeeperHistReg#8]
I would like to reproduce the results on the ANHIR dataset, how do I prepare the dataset?Specifically, how do I set up the source_path and target_path? Is it only possible to align single picture？ it seems to be different from the previous DeeoHistReg version?
Finally, how can I train my own dataset？
Thank you. Best to you

**Comment by MWod** [comment]
Hello,

The framework is dedicated to register any WSIs and is not limited to any particular dataset. If you want register e.g. ANHIR dataset, you need to implement your own logic to iterate over the registration pairs and then use the framework as presented in the example.

This framework is completely different than DeepHistReg. DeeperHistReg is universal registration tool while the DeepHistReg repository was implemented using ANHIR directly.

You do not need to perform any training to use the framework (the framework does not need retraining or fine-tuning). You just set the paths and register the slides. 

Bests,

**Comment by LuoSihao-Simon** [comment]
> Hello,
> 
> The framework is dedicated to register any WSIs and is not limited to any particular dataset. If you want register e.g. ANHIR dataset, you need to implement your own logic to iterate over the registration pairs and then use the framework as presented in the example.
> 
> This framework is completely different than DeepHistReg. DeeperHistReg is universal registration tool while the DeepHistReg repository was implemented using ANHIR directly.
> 
> You do not need to perform any training to use the framework (the framework does not need retraining or fine-tuning). You just set the paths and register the slides.
> 
> Bests,

Thank you very much for your detailed response. I have a follow-up question regarding the generalization of the framework. Since the framework does not require retraining or fine-tuning, I’m wondering how well it generalizes to other datasets for WSI registration. Specifically, does the effectiveness of the registration decrease on different datasets if the framework is not trained on them? How robust is the universal network across various types of data? I will conduct my own experiments to verify this, but I’d like to first understand your explanation from a methodological perspective.
I appreciate your guidance and I look forward to applying this to my own work
Thanks again for your support and best wishes to you : ）

**Comment by MWod** [comment]
It generalizes to other datasets very well - it should be possible to register any H&E and IHC stains (and in fact also others, e.g. ExM or DAPI). The effectiveness of the registration should not decrease when new data is registered (the displacement fields are fine-tuned using instance optimization).

To check how the default methods work, please see: https://www.sciencedirect.com/science/article/pii/S0169260724001834

Bests,

**Comment by LuoSihao-Simon** [comment]
Thank you for your clarification regarding the framework's generalization capabilities. I have read the paper you shared and will be trying your algorithm on fluorescence-stained data. We expect the method to work well, and we will ensure to cite all your related works in our research.
Thanks again for your support!
Bests,

**Comment by LuoSihao-Simon** [comment]
> It generalizes to other datasets very well - it should be possible to register any H&E and IHC stains (and in fact also others, e.g. ExM or DAPI). The effectiveness of the registration should not decrease when new data is registered (the displacement fields are fine-tuned using instance optimization).
> 
> To check how the default methods work, please see: https://www.sciencedirect.com/science/article/pii/S0169260724001834
> 
> Bests,

Thank you for your clarification regarding the framework's generalization capabilities. I have read the paper you shared and will be trying your algorithm on fluorescence-stained data. We expect the method to work well, and we will ensure to cite all your related works in our research.
Thanks again for your support!
Bests,
