### ISSUE TITLE
How to evaluate on my own dataset

### ISSUE THREAD

**Issue by LuoSihao-Simon** [MWod/DeeperHistReg#9]
I would like to know how to evaluate my results after alignment? I don't see any executable code for testing and evaluation, and I can't test the accuracy of the alignment on my own dataset.
Thank u, all the best :)

**Comment by MWod** [comment]
Hello,

Everything depends on how you want to perform the evaluation - there are several options (visual inspection, target registration error, foldings, Dice/HD if segmentation masks are available). However, every dataset has different conventions about the landmarks or segmentations representation, therefore it is impossible to propose a universal evaluation script.

You can evaluate the registration quality by using the [apply_deformation](https://github.com/MWod/DeeperHistReg/blob/main/deeperhistreg/dhr_deformation/apply_deformation.py#L39) function to the segmentation mask or by warping the registration landmarks, e.g.:

```
def warp_landmarks(landmarks, displacement_field, postprocessing_params):
    source_pad = postprocessing_params['pad_1']
    target_pad = postprocessing_params['pad_2']
    source_resample_ratio = postprocessing_params['source_resample_ratio']
    target_resample_ratio = postprocessing_params['target_resample_ratio']
    initial_resampling = postprocessing_params['initial_resampling']
    if initial_resampling:
        initial_resample_ratio = postprocessing_params['initial_resample_ratio']
    y_pad = target_pad[0]
    x_pad = target_pad[1]
    landmarks = landmarks * target_resample_ratio
    landmarks[:, 0] = landmarks[:, 0] + x_pad[0]
    landmarks[:, 1] = landmarks[:, 1] + y_pad[0]
    if initial_resampling:
        landmarks = landmarks / initial_resample_ratio
    warped_landmarks = w.warp_landmarks(landmarks, displacement_field)
    if initial_resampling:
        warped_landmarks = warped_landmarks * initial_resample_ratio
    y_pad = source_pad[0]
    x_pad = source_pad[1]
    warped_landmarks[:, 0] = warped_landmarks[:, 0] - x_pad[0]
    warped_landmarks[:, 1] = warped_landmarks[:, 1] - y_pad[0]
    warped_landmarks = warped_landmarks / source_resample_ratio
    return warped_landmarks
```
where the required `displacement_field` and `postprocessing params` are saved in the results folder.

Bests,

**Comment by LuoSihao-Simon** [comment]
> Hello,
> 
> Everything depends on how you want to perform the evaluation - there are several options (visual inspection, target registration error, foldings, Dice/HD if segmentation masks are available). However, every dataset has different conventions about the landmarks or segmentations representation, therefore it is impossible to propose a universal evaluation script.
> 
> You can evaluate the registration quality by using the [apply_deformation](https://github.com/MWod/DeeperHistReg/blob/main/deeperhistreg/dhr_deformation/apply_deformation.py#L39) function to the segmentation mask or by warping the registration landmarks, e.g.:
> 
> ```
> def warp_landmarks(landmarks, displacement_field, postprocessing_params):
>     source_pad = postprocessing_params['pad_1']
>     target_pad = postprocessing_params['pad_2']
>     source_resample_ratio = postprocessing_params['source_resample_ratio']
>     target_resample_ratio = postprocessing_params['target_resample_ratio']
>     initial_resampling = postprocessing_params['initial_resampling']
>     if initial_resampling:
>         initial_resample_ratio = postprocessing_params['initial_resample_ratio']
>     y_pad = target_pad[0]
>     x_pad = target_pad[1]
>     landmarks = landmarks * target_resample_ratio
>     landmarks[:, 0] = landmarks[:, 0] + x_pad[0]
>     landmarks[:, 1] = landmarks[:, 1] + y_pad[0]
>     if initial_resampling:
>         landmarks = landmarks / initial_resample_ratio
>     warped_landmarks = w.warp_landmarks(landmarks, displacement_field)
>     if initial_resampling:
>         warped_landmarks = warped_landmarks * initial_resample_ratio
>     y_pad = source_pad[0]
>     x_pad = source_pad[1]
>     warped_landmarks[:, 0] = warped_landmarks[:, 0] - x_pad[0]
>     warped_landmarks[:, 1] = warped_landmarks[:, 1] - y_pad[0]
>     warped_landmarks = warped_landmarks / source_resample_ratio
>     return warped_landmarks
> ```
> 
> where the required `displacement_field` and `postprocessing params` are saved in the results folder.
> 
> Bests,

Thank you for your detailed explanation and for providing the code snippet for evaluating registration quality. I will proceed with evaluating my results as suggested ：）
Thanks again, and all the best to you!
